# base settings
typeset -g POWERLEVEL9K_MODE=nerdfont-complete
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir command_execution_time vcs)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()


# os icon settings
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND="#cdd6f4"
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=""
typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION="󰣇 $USER"


# dir settings
typeset -g POWERLEVEL9K_DIR_CLASSES=(
  "/"                ROOT    "in"
  "~"                HOME    "in"
  "*"                DEFAULT "in"
)
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_last
typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=""
typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=0
typeset -g POWERLEVEL9K_DIR_FOREGROUND="#cdd6f4"
typeset -g POWERLEVEL9K_DIR_HOME_FOREGROUND="#cdd6f4"
typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="#cdd6f4"
typeset -g POWERLEVEL9K_DIR_BACKGROUND=""
typeset -g POWERLEVEL9K_DIR_HOME_BACKGROUND=""
typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND=""


# separator settings
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=""
typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=""
typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=""
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=""
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=""
typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL=""
typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=""
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=""


# whitespace settings
typeset -g POWERLEVEL9K_OS_ICON_LEFT_LEFT_WHITESPACE=""
typeset -g POWERLEVEL9K_OS_ICON_LEFT_RIGHT_WHITESPACE=" "
typeset -g POWERLEVEL9K_DIR_LEFT_LEFT_WHITESPACE=" "
typeset -g POWERLEVEL9K_DIR_LEFT_RIGHT_WHITESPACE=" "
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_LEFT_LEFT_WHITESPACE=" "
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_LEFT_RIGHT_WHITESPACE=" "
typeset -g POWERLEVEL9K_VCS_LEFT_LEFT_WHITESPACE=" "
typeset -g POWERLEVEL9K_VCS_LEFT_RIGHT_WHITESPACE=""
typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_LEFT_WHITESPACE=" "
typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_RIGHT_WHITESPACE=""


# enable line spacing
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true


# transient prompt settings
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT_LEFT_PROMPT_ELEMENTS=(prompt_char)
typeset -g POWERLEVEL9K_TRANSIENT_PROMPT_RIGHT_PROMPT_ELEMENTS=()
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_{VIINS,VICMD,VIVIS}_CONTENT_EXPANSION=""
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_{VIINS,VICMD,VIVIS}_FOREGROUND="white"
typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_{VIINS,VICMD,VIVIS}_BACKGROUND=""


# enable two-line prompt
typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=true
typeset -g POWERLEVEL9K_LPROMPT_ON_NEWLINE=true
typeset -g POWERLEVEL9K_RPROMPT_ON_NEWLINE=false


# lines separator settings
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="╭─ "
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="╰─ "
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=""
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=""
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX_FOREGROUND="#cdd6f4"
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX_FOREGROUND="#cdd6f4"
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX_FOREGROUND=""
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX_FOREGROUND=""


# command execution time settings
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT="d h m s"
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="#cdd6f4"
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=""
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_ICON=""
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_VISUAL_IDENTIFIER_EXPANSION="took"


# vcs settings
typeset -g POWERLEVEL9K_VCS_FOREGROUND="#7f849c"
typeset -g POWERLEVEL9K_VCS_BACKGROUND=""
typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION=""
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=""
typeset -g POWERLEVEL9K_VCS_MODIFIED_ICON="!"
typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON="󰆢"
typeset -g POWERLEVEL9K_VCS_ADDED_ICON=""
typeset -g POWERLEVEL9K_VCS_RENAMED_ICON=""
typeset -g POWERLEVEL9K_VCS_DELETED_ICON=""
typeset -g POWERLEVEL9K_VCS_CONFLICT_ICON=""
typeset -g POWERLEVEL9K_VCS_STASH_ICON=""
